### PR TITLE
add support for sonar authorization (token or username/password)

### PR DESCRIPTION
**Pull request by r0bb3n**
This PR adds support for basic auth with token or username/password ([SonarQube Docs - Web API Authentication](https://docs.sonarqube.org/latest/extend/web-api/)) by reading the same properties that are required by sonar plugin: `sonar.login` and `sonar.password`

### CODE REVIEW

**Comment by pethers** [comment]
Recommend using https://github.com/adnovum/sonar-build-breaker, better implemented and don't require developer effort to enable it across projects.

**Comment by pethers** [comment]
But happy to release it, so thanks for the pull request.

**Comment by pethers** [comment]
Released it now https://github.com/Hack23/sonar-quality-gates-maven-plugin/releases/tag/sonar-quality-gates-maven-plugin-1.0.5 , pushed to https://oss.sonatype.org/ and should be at maven central shortly.

**Comment by r0bb3n** [comment]
> 
> 
> Recommend using https://github.com/adnovum/sonar-build-breaker, better implemented and don't require developer effort to enable it across projects.

Unfortunately I have no admin access to that sonarqube and getting a plugin installed is complicated, that's the my reason for solving it on client/project-side. ;-)

**Comment by pethers** [comment]
Get it, also easier to opt in to use quality gate initially. 

This plugin might require a "sleep 10" or similar after running the sonar scan. Just happy it is useful for somebody.

Assumes the analysis of the project is completed. Missing logic like https://github.com/adnovum/sonar-build-breaker/blob/master/src/main/java/org/sonar/plugins/buildbreaker/QualityGateBreaker.java that checks if the scan is completed. For small projects rarely noticed.

**Pull request merged**
